### ISSUE TITLE
Extended versioning

### ISSUE THREAD

**Issue by kweij** [Vinai/compressed-magento-sample-data#3]
Hi,

Besides finding this compressed sample data archive a great idea, I have a little request. Now this repo contains links to sample data for version 1.9.0.0 and 1.9.1.0. Could this be extended with a link to version 1.9.0.1, regardless of whether the content is exactly the same as for version 1.9.0.0. See, I'd like to be able to check automatically for the compressed sample data for a certain version of Magento.

Thanks in advance,
Klaas

**Comment by Vinai** [comment]
I don't want to bloat the repository with multiple copies of the same files.
However, creating a mapping from a Magento version to the appropriate sample data version would make sense.
Adding a json file containing the mapping would make it easily scriptable.
Or, casual shell scriptability, I suggest creating a directory magento-to-sample-data-map/ with one file per Magento version, containing only the appropriate sample data version.
That way you could do
```bash
MAGE_VERSION=1.9.0.1
SAMPLE_DATA_VERSION=$(curl https://raw.githubusercontent.com/Vinai/master/magento-to-sample-data-map/$MAGE_VERSION)
WGET https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/$SAMPLE_DATA_VERSION/compressed-magento-sample-data-$SAMPLE_DATA_VERSION.tbz
```
Please feel free to submit a PR with whatever suits your needs the most.

**Comment by kweij** [comment]
I like that last idea. It suits my needs exactly. I'll have a go at it ..

**Comment by Vinai** [comment]
Thanks, looking forward to a PR!

**Comment by kweij** [comment]
Sorry for being a bit late, thanks for the merge!
