### ISSUE TITLE
Issue with load of this sample data into Magento

### ISSUE THREAD

**Issue by vmitt** [Vinai/compressed-magento-sample-data#6]
While installing Magento for the sample data shared by Vinai, I am getting an error where it is not finding the table core_theme in the MySQL database.

I used Magento2 from the github and used the sample data listed by Vinai.

Is it because of versioning issue of Magento tool or something else ??

**Comment by Vinai** [comment]
This sample data is for Magento 1 only, it can not be used with Magento 2.
The Magento 2 sample data can be installed via composer, it should be possible to google it.
